name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.TOKEN}}
              
      - name: Build the Docker image
        run: | 
          docker build . -f ./build/Dockerfile --tag alert-service:$(git rev-parse --short HEAD)
          docker push ghcr.io/gagraler/alert-service:$(git rev-parse --short HEAD)
